### PR TITLE
Updated the goamz cloudwatch API to sync up with the fixes for

### PR DESCRIPTION
**Pull request by levb**
Dimensions and StatisticSet,

See https://github.com/crowdmob/goamz/commit/e9a919b6da95151fc77b1b7bb3e78a8a68379aa1

### CODE REVIEW

**Comment by rafrombrc** [comment]
Thanks for your contribution! Sorry it's taken so long for this to be reviewed. Delays aside, I've finally gotten a chance to test this. Unfortunately, the tests fail even when I've updated all of the software versions with the following error:

```
thor [heka] git:levb-fix-cloudwatch ~/go/heka $ go test -v github.com/mozilla-services/heka-mozsvc-plugins
=== RUN TestAllSpecs
2014/01/22 11:10:32 Missing EXPECT() for invoked function: *pipelinemock.MockInputRunner.LogError([No Namespace specified])
/home/rob/go/heka/build/heka/src/code.google.com/p/gomock/gomock/controller.go:112 (0x534ae4)
    google.com/p/gomock/gomock.(*Controller).Call: stack := debug.Stack()
/home/rob/go/heka/build/heka/src/github.com/mozilla-services/heka/pipelinemock/mock_inputrunner.go:73 (0x5385ff)
    com/mozilla-services/heka/pipelinemock.(*MockInputRunner).LogError: _m.ctrl.Call(_m, "LogError", _param0)
/home/rob/go/heka/build/heka/src/github.com/mozilla-services/heka-mozsvc-plugins/cloudwatch.go:213 (0x43a064)
    com/mozilla-services/heka-mozsvc-plugins.(*CloudwatchInput).Run: ir.LogError(err)
/home/rob/go/heka/build/heka/src/github.com/mozilla-services/heka-mozsvc-plugins/cloudwatch_test.go:147 (0x441b4d)
    com/mozilla-services/heka-mozsvc-plugins.func.007: input.Run(ith.MockInputRunner, ith.MockHelper)
/usr/local/go/src/pkg/runtime/proc.c:1394 (0x418680)
    goexit: runtime·goexit(void)

exit status 1
FAIL    github.com/mozilla-services/heka-mozsvc-plugins 0.011s
```

The underlying cause is that the call to `cwi.cw.GetMetricStatistics` on line 211 in cloudwatch.go is failing b/c the req struct doesn't have a Namespace value set.

For future reference, in the PR that you submit to the heka project, you can update the SHA for both the upstream dependency (goamz in this case) and the heka-mozsvc-plugins project (to the commit that is on your branch) to make sure that the CI tests will be run with the correct versions of both packages.

If you wouldn't mind resolving this issue and updating both PRs so we have a consistent build that passes all the tests I'd be happy to merge. :)

**Comment by levb** [comment]
Updated https://github.com/mozilla-services/heka/pull/614 with this commit's SHA; fixed the failing test; not sure how I get to see the CI results, but the above-mentioned go test now succeeds

**Comment by rafrombrc** [comment]
Usually the CI results show up on this Pull Request page directly, but sometimes (like now, apparently) things get a bit out of whack and it stops showing up. In that case you can visit https://travis-ci.org/mozilla-services/heka and click on the "Pull Requests" tab to see the build results for each PR.

**Comment by rafrombrc** [comment]
Whoops, my bad... you can't see the CI output on this page, this is the heka-mozsvc-plugins project. You _can_ see the CI output on the PR pages for Heka itself (e.g. https://github.com/mozilla-services/heka/pull/614), which happen to build and test heka-mozsvc-plugins as well as the Heka core.

**Comment by rafrombrc** [comment]
And, duh, the travis build is currently failing, not b/c you did anything wrong, but b/c the heka-mozsvc-plugins SHA in question doesn't exist in our repo until this PR is merged. Forgot about that wrinkle, since internally we usually use branches inside this repo rather than forks. Sorry for the noise, I'll check out all of the code manually to verify the tests are passing and will merge if so.

**Pull request merged**
